### ISSUE TITLE
Branch & PR builds triggered despite configuration

### ISSUE THREAD

**Issue by nightowlengineer** [jenkinsci/bitbucket-branch-source-plugin#209]
### Your checklist for this issue

- [x] Jenkins version: 2.181

- [x] Plugin version: 2.4.4

- [x] Bitbucket server version: 5.16

### Description

I have an organisation folder configured to discover all change/pull requests & branches, but only build PRs (ignoring 'target branch' changes) and master (branch exact name).

However, after merging a PR to master, a number of builds are triggered. Some are branch builds (which should not be happening - only discovery), some are PRs (which I believe should also not be happening, as I've disabled rebuild on target change).

I can see the branch event being received from Bitbucket by Jenkins which then schedules a build, but I can't understand why. I'm convinced it did not used to behave this way and is a recent change or regression.

This issue causes numerous builds to occur and ties up our CI service.

**Comment by jimklimov** [comment]
I see a similar behavior, with several Jenkins server versions starting about half a month ago. We did have similar issues earlier with BB and Github organization jobs, which I am not sure are directly related or just looked similar (back then, we had loops of rebuilding a failed Github commit - now we have successful builds redone thousands of times until a PR gets merged; and we did have some similar issues with Bitbucket that were worked around by not looking at "merge" PR jobs - and then those were re-enabled and worked OK for the past year or so).

Looking at the current situation, the pattern for reproduction seems to be that our developers have a fork of some "upstream" codebase, with auto-sync from the upstream enabled (if it matters), and make a "quick fix" PR right from their same-named branch (e.g. "master"). The issue only impacts "PR-XX-merge" jobs but not "PR-XX-head" ones  (so maybe some on-premise Bitbucket v5.14.1 REST API issue? still, the virtual merge-commit hash stays the same...)

As an experiment, I posted two PRs with the same commit, one from a recently updated master branch in my fork of a project, and another in an arbitrarily named branch (copy of my same local master state with the PRed change)... the former, a PR from my master branch, has gone on to a second build and a third is queued by now. The latter seems satisfied with having built once.

The jobs we've had looping previously looked like this in our `jenkins.log` :
````
2019-07-29 09:10:47.165+0000 [id=944]   INFO    h.triggers.SCMTrigger$Runner#run: SCM changes detected in Stash » component1 » PR-29-merge. Triggering  #892
2019-07-29 09:10:47.172+0000 [id=988]   INFO    h.triggers.SCMTrigger$Runner#run: SCM changes detected in Stash » component2 » PR-2-merge. Triggering  #2655
````

...with previously logged (thousands of) successes like
````
2019-07-29 09:05:18.312+0000 [id=128404]        INFO    o.j.p.workflow.job.WorkflowRun#finish: Stash/component1/PR-29-merge #890 completed: SUCCESS
````

There were a number of jobs in similar loop that failed for external reasons and were not retried since.

A manual abort does nothing to the loop, another copy gets on soon, even if wiped from both queue and running build lists.

Having the jobs throttled to run one copy simultaneously somewhat helps contain the workload (a component that did not have such limitation saturated all available build agents).

CURRENT WORKAROUNDS that seem to help us somewhat:
* do not post PRs from "master" branches (or maybe any other branch named same as in the target codebase)
* have an `options { disableConcurrentBuilds() }` in the `Jenkinsfile`
* if in this situation already, (temporarily) disable building PR "merge" subtype jobs, and get those PRs from/to same-named branches merged (or closed and reposted) ASAP.

**Comment by nicholascus** [comment]
Would you be able to resolve your problem with Basic Branch Build Strategies Plugin ?
![image](https://user-images.githubusercontent.com/1756853/62930318-8825ce80-bdff-11e9-87f2-98400de17cf2.png)

**Comment by jimklimov** [comment]
Hello @nicholascus and sorry for a late response.

I did not check yet if the build strategy would help, though it might be a reasonable workaround as well. If a CI deployment does enable "PR-merge" builds it is done to ensure that the scrum team or release engineers have a peace of mind that hitting that "Merge" button does not break anything. In many cases it is also part of configured branch protection strategy on an SCM platform like bitbucket or github (e.g. to not disrupt final-release branches with uncertain changes).

So if the target branch (e.g. master) marched on after the PR was posted, the virtual merge-commit hash (and virtual codebase content) does change, so such events should be rebuilt if we are in business of doing the merge-builds at all.

What should not happen, at least per my comments/observations above, is continuous requeues and rebuilds of the same (virtual) commit that has just been built with whatever outcome. At a minimum, the rebuilds should not happen after this commit has a known verdict. Optimally, it should only be queued once per BuildCause and related conditions (repo/branch name, etc.). I mean, same HEAD hash in PR-build context and master-branch context can have different outcomes, depending on the Jenkinsfile and other recipes and settings involved, so the solution should be careful to not just enforce blocking same-hash rebuilds ever :)

**Comment by nightowlengineer** [comment]
Pinging to avoid closure

**Comment by qalinn** [comment]
Hello! 

I have the same issue. Do you have any updates or workaround for the issue ?

**Comment by casz** [comment]
This plugin relies on contributions done by users.

**Comment by qalinn** [comment]
I have a bitbucket server 5.2.2 and I cannot manage to trigger a build from bitbucket to jenkins.
 I can see the notification from bitbucket: Received notification from "ip adress" ⇒ https://jenkins.url/git/notifyCommit for uri = https://gitURL/scm/ARC/testbitbucket.git ; sha1 = 26b08cedb697a24a6c6233a22ed288a3bd3ff7ab ; branches = [branch10]
But the jenkins doesn't start to create a new build for this notification. 
If I am creating a new branch and I am pushing on bitbucket, the jenkins is notified but the job is not created on bitbucket team organization folder.
