### ISSUE TITLE
SSH Credentials are not available on branch sources

### ISSUE THREAD

**Issue by marcelaraujo** [jenkinsci/bitbucket-branch-source-plugin#266]
### Your checklist for this issue

- [x] Jenkins version
- [x] Plugin version
- [] Bitbucket cloud
- [x] Bitbucket server and version

### Description
Jenkins: 2.206
Plugin: 2.6.0
Bitbucket server and version: 6.7.1

It's not possible to use SSH credentials on branch sources configurations, only https.

Is there a reason or it is a bug?

**Comment by alexandersels** [comment]
Did you manage to find a solution to this issue yet ? I'm facing the exact same problem ..

**Comment by marcelaraujo** [comment]
I did @alexandersels. When I got back home, I let you know what I did :)

**Comment by alexandersels** [comment]
Cool ! Looking forward for the feedback :)

**Comment by marcelaraujo** [comment]
@alexandersels the process flow is

* Use https to check repository informations though repository server API (Bitbucket in my case)
* Use https or ssh to fetch project

I'm using DSL to create my pipelines

```
branchSources {
                branchSource {
                    source {
                        bitbucket {
                            serverUrl("https://xxx.yyy.zzz")
                            credentialsId("repository_api_reader")
                        }
                    }
                }
            }

            configure { node ->
                def traits = node / sources / data / 'jenkins.branch.BranchSource' / source / traits
                traits << 'com.cloudbees.jenkins.plugins.bitbucket.SSHCheckoutTrait' {
                    credentialsId("repository_fetch_ssh")
                }
            }
```

But it is possible to configure manually following these instructions

![image](https://user-images.githubusercontent.com/421794/74657673-a5f63680-5188-11ea-8a0e-729a008dde8b.png)

You gonna need two credentials

**Comment by alexandersels** [comment]
Hey Marcel,

Thank you for the update ! We have indeed tried to create username / pw credentials. However, we seemed to have stumbled upon a different issue now. When trying to connect to the rest api of our repository we keep on getting 401 responses ... We added our credentials, tried to use app password instead of password but nothing seems to work. 

You don't have any idea by any chance ?

**Comment by nashpaz123** [comment]
Goood this was hard to figure out. When trying to use 
```
sshagent(['npazsshid']) {
                    sh(""" git push --tags 
""")
```
I kept getting:
`fatal: could not read Username for 'https://bitbucket.org': No such device or address
`and had no idea what was wrong. Turns out you just have to checkout with SSH in order for the push with SSH to be available to sshagent. Thanks!
