### ISSUE TITLE
Support bitbucket api auth with token

### ISSUE THREAD

**Issue by af6140** [jenkinsci/bitbucket-branch-source-plugin#289]
### Your checklist for this issue

- [ ] Jenkins version
any
- [ ] Plugin version
latest
- [ ] Bitbucket cloud

- [ ] Bitbucket server and version
any

### Description
Bitbucket server support request api token auth, this is more convenient in enterprise environment then user and password.

**Comment by Zauxst** [comment]
Hi, not the maintainer here.

You can create a personal access token and use that to authenticate, instead of using a password. The benefit would be that you would not have to change the password every time the account passwords changes in the User Directory.

You have to pass the token in the password field instead of the account password. The username must still be specified.

**Comment by mikeboutch** [comment]
That is really a BAd news
