### ISSUE TITLE
Ignore committers does not work

### ISSUE THREAD

**Issue by reitzmichnicht** [jenkinsci/bitbucket-branch-source-plugin#367]
### Your checklist for this issue
- [x] Jenkins version
2.249.1
- [x] Plugin version
2.9.2
- [x] Bitbucket server and version
Bitbucket Server 6.6.1

### Description
Setting ignored committers for a multibranch pipeline with a bitbucket source does not work. The description says the webhook is configured accordingly, but the integrated webhook approach in bitbucket server does not allow this setting.
We really need this feature to ignore the Jenkins as committer itself or ignore by commit message.

Kind regards,
Michael

**Comment by bitwiseman** [comment]
@reitzmichnicht  Which "ignored committers" setting?   Could show a screenshot?

**Comment by reitzmichnicht** [comment]
![branch source](https://user-images.githubusercontent.com/2757515/93142356-1f85e100-f6e6-11ea-9ae9-a60cf9c199ee.png)
This is a checkout behaviour setting

**Comment by bitwiseman** [comment]
@reitzmichnicht 
Ah, you're using this: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/b5a8011f6a03cc8860f2c8ebd039f44086f31d6a/src/test/java/com/cloudbees/jenkins/plugins/bitbucket/WebhookConfigurationTraitTest.java

Have you looked at https://github.com/jenkinsci/ignore-committer-strategy-plugin ?

**Comment by reitzmichnicht** [comment]
I'll take a look and test it, was not aware that it supports organizationalFolder of bitbucket as its a bit outdated.

Nonetheless the provided bitbucket trait ignore committers seems to be legacy for not native webhooks?

**Comment by bitwiseman** [comment]
@reitzmichnicht

> Nonetheless the provided bitbucket trait ignore committers seems to be legacy for not native webhooks?  

I'm not sure.  I don't have bandwidth to delve much on this issue currently.

**Comment by ryancurrah** [comment]
The plugin https://github.com/jenkinsci/ignore-committer-strategy-plugin is def what your looking for. I made the same mistake when I started.

**Comment by xtroce** [comment]
I ran into the same problem, with configuring the ignored commiter and it not being working diving into debugging. Wouldn't it be better to remove the internal plugin and just mentioning in the documentation that if you should use another plugin to do that, instead of leaving an essentially non working function in the code?

**Comment by diegosep** [comment]
Hi, I confirm, this feature of the plugin is not working, I tried either email, name, or more options and it does not work.

**Comment by Shasthri** [comment]
I can confirm too that this feature is not working for us.

**Comment by pvvarfalameev** [comment]
any updates?

**Comment by nicolasaigner** [comment]
Any feedback on this? I have the same problem and I don't want to install other plugins.

**Comment by jaunusa** [comment]
Having the same issue trying to ignore committers with this plugin using v7.x for server version, running Bitbucket version v7.21.10.
Switching to "Plugin" at "Webhook implementation to use" does not create webhooks in Bitbucket repository and throws a Jenkins warning:
```
Mar 15, 2023 10:04:01 AM WARNING org.apache.http.client.protocol.ResponseProcessCookies processCookies
Invalid cookie header: "Set-Cookie: BITBUCKETSESSIONID=XXXXXX; Max-Age=1209600; Expires=Wed, 29 Mar 2023 09:04:01 GMT; Path=/; Secure; HttpOnly". Invalid 'expires' attribute: Wed, 29 Mar 2023 09:04:01 GMT
Mar 15, 2023 10:04:01 AM WARNING com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1 doRun
Could not register hooks for MIS Group/misreport
java.io.FileNotFoundException: URL: /rest/webhook/1.0/projects/MISG/repos/misreport/configurations
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:879)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getWebHooks(BitbucketServerAPIClient.java:733)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHook(WebhookAutoRegisterListener.java:167)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:133)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:56)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:102)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:94)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by capeflynn** [comment]
Does anyone know if there are plans to fix this issue or if there is already a workaround we could use?

**Comment by CJCombrink** [comment]
Any updates on this? 
Also having the same issue, I can't get the "Set ignored committers" to work and would really like to have this functionality

**Comment by nfalco79** [comment]
> The description says the webhook is configured accordingly, but the integrated webhook approach in bitbucket server does not allow this setting.

Have a look to [this my comment](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/863#issuecomment-2495461918) please.

> Is there are Plugin needed on Bitbucket when using Plugin for "Webhook implementation to use" in Jenkins config?

It's this one https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket?tab=overview&hosting=datacenter

**This traits settings is valid only to be used in the web hook configuration.**
It's not a build strategy designed instead to avoid trigger the build when a web hook notification comes from a specific committer author or message. To archive have a look to [this plugin](https://github.com/jenkinsci/ignore-committer-strategy-plugin)

I will open a PR to better describe the trait and add some documentation.

Personally I don't understand why this plugin implements specific APIs for a non-free plugin preferring it over others available on the market ([this](https://marketplace.atlassian.com/apps/1211284/webhook-to-jenkins-for-bitbucket?hosting=cloud&tab=overview) for example).
The maintenance cost now falls on developers both in terms of managing issues and keeping APIs up to date, for example those in use are API version 1.0 but there are 2.0 which have different payloads.

I would plan a story to provide an extension point so that anyone can provide a specific implementation for a plugin (their own or not) webhook other than the one provided by Atlasstian (cloud or server).
