### ISSUE TITLE
add-support-to-pr:reviewer:approved-event

### ISSUE THREAD

**Issue by MayaPetter** [jenkinsci/bitbucket-branch-source-plugin#428]
- [x ] Jenkins version 2.229

- [x ] Plugin version 2.9.7

- [x ] Bitbucket server and version 6.4.0

### Description

add support to pr:reviewer:approved event - SERVER_PULL_REQUEST_APPROVED

**Comment by wahammed** [comment]
Is this feature available on Bit Bucket cloud yet?

**Comment by MayaPetter** [comment]
Hi,

I don't know, but I the plugin is up for adoption and no one has replied to
my pull request....

**Comment by wahammed** [comment]
@MayaPetter Since this is not merged. How are you achieving this one with Jenkins and Bit Bucket?

**Comment by MayaPetter** [comment]
I changed the plugin locally and use the new jar, after this pull request
will be merged I'll change Jenkins to use this plugin

**Comment by wahammed** [comment]
I tried to do the same however not able to make approve post Jenkins job is successful. Is there any additional steps you have done?

**Comment by MayaPetter** [comment]
No... Also don't know who to contact to approve the pull request

**Comment by nfalco79** [comment]
The description of this feature request is too sparse and does not capture the motivation, the goal that is being achieved. Such an event currently generates a global reindex since it does not contain any (source) changes. I ask because there are several discussions about the problem of events that do not bring changes triggering reindexes that cause a "build storm", especially when repositories are very large.
So unless there is a strong motivation and a practical example of utility, it will close the request and its PR
