### ISSUE TITLE
Duplicate triggered builds on Pull-Requests

### ISSUE THREAD

**Issue by lifeofguenter** [jenkinsci/bitbucket-branch-source-plugin#508]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.303.2
Bitbucket Branch Source Plugin  2.9.11
```

### Reproduction steps

Pushing a commit with Bitbucket DC 7.17.1 will cause two webhooks (NATIVE) to be sent:

```
[Fri Nov 12 13:01:46 UTC 2021] com.cloudbees.jenkins.plugins.bitbucket.hooks.NativeServerPullRequestHookProcessor$HeadEvent UPDATED event from 10.230.216.151 ⇒ https://foobar/bitbucket-scmsource-hook/notify with timestamp Fri Nov 12 13:01:46 UTC 2021 processed in 0.2 sec
[Fri Nov 12 13:01:47 UTC 2021] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.NativeServerPushHookProcessor$HeadEvent UPDATED event from 10.230.200.222 ⇒ https://foobar/bitbucket-scmsource-hook/notify with timestamp Fri Nov 12 13:01:46 UTC 2021
```

This seems (and expected) fine in other setups, but for some reason in the current setup this will result in duplicate builds in our Jenkins.

Any guidance on why this causes a duplicate build on some commits but not on others would be really nice :)

**Comment by KalleOlaviNiemitalo** [comment]
Are 10.230.216.151 and 10.230.200.222 two nodes of your Bitbucket Data Center cluster?

I hypothesize that this is a race condition in Jenkins -- that Jenkins processes the duplciate webhooks in parallel threads and each thread detects that the head commit is different from what it was before. This might happen more frequently if the Jenkins controller is under heavier load. If this hypothesis is correct then adding some kind of lock ought to fix it. I don't know whether the lock would belong in bitbucket-branch-source, scm-api, or branch-api.

[JENKINS-43353](https://issues.jenkins.io/browse/JENKINS-43353) at least provides an easy way to abort the duplicate build so that it doesn't needlessly consume resources.

**Comment by lifeofguenter** [comment]
Thanks @KalleOlaviNiemitalo for the info.

We unfortunately can not abort duplicate builds as they might cause issues (for example terraform), but for now we can mitigate it by setting the `quietPeriod` to something like 2.

One thing I noticed though: Bitbucket is registering (Native) a lot of events. With GitHub usually you only register "push" and "pr".

When I do the same for Bitbucket Server, builds still work, but at least I do not get multiple events for the same:

![Screenshot 2021-11-12 214842](https://user-images.githubusercontent.com/241073/141532606-573a9375-a7ca-47b4-a3d0-86f9bbaab7e2.png)
