### ISSUE TITLE
Send Junit Tests to Bitbuckt Reports

### ISSUE THREAD

**Issue by sanguis** [jenkinsci/bitbucket-branch-source-plugin#522]
### Feature Request

If any junit tests are created in the Jenkins build, send a report to the commit.
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bcommit%7D/reports/%7BreportId%7D#put

**Comment by nilsmahlstaedt** [comment]
or make it one of the pipeline behaviours you can set.
Then you could also config the path (maybe ant glob pattern) to search in for report xml's

**Comment by nfalco79** [comment]
I think this request is out of scope for this plugin. The main goal of this plugin is to set up an SCM for source code checkout. What happens after checkout depends on another build or publishing step.

As @KalleOlaviNiemitalo said, there is a specific API plugin called [Checks API](https://plugins.jenkins.io/checks-api/) that provides the requested functionality (publishing results). Currently only GitHub and Gitea are supported, provided by two separate plugins. To support Bitbucket, you need to create a new Checks API implementation plugin. It doesn't make sense to implement it here, like not even e.g. github-source-plugin did.
After that, since the JUnit/XUnit publisher already supports publishing via Checks API, you're done
