### ISSUE TITLE
Use CANCELLED build state in Bitbucket Data Center and Server 8.0

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkinsci/bitbucket-branch-source-plugin#606]
### What feature do you want to see added?

[Bitbucket Data Center and Server 8.0](https://confluence.atlassian.com/bitbucketserver/bitbucket-data-center-and-server-8-0-release-notes-1115659343.html) support two new build states: UNKNOWN and CANCELLED. Please map the Jenkins ABORTED result to CANCELLED when the on-premises Bitbucket software is sufficiently new.

Bitbucket Branch Source 751.vda_24678a_f781 maps the results as follows:

| Jenkins | Bitbucket Cloud | Bitbucket Data Center and Server |
| --- | --- | --- |
| [SUCCESS](https://javadoc.jenkins.io/hudson/model/Result.html#SUCCESS) | SUCCESSFUL | SUCCESSFUL |
| [UNSTABLE](https://javadoc.jenkins.io/hudson/model/Result.html#UNSTABLE) | configurable SUCCESSFUL or FAILED | configurable SUCCESSFUL or FAILED |
| [FAILURE](https://javadoc.jenkins.io/hudson/model/Result.html#FAILURE) | FAILED | FAILED |
| [NOT_BUILT](https://javadoc.jenkins.io/hudson/model/Result.html#NOT_BUILT) | configurable SUCCESSFUL or STOPPED | configurable SUCCESSFUL  or nothing 👈 |
| [ABORTED](https://javadoc.jenkins.io/hudson/model/Result.html#ABORTED) | FAILED | FAILED 👈 |
| null | INPROGRESS | INPROGRESS |

CANCELLED would be suitable for the ABORTED result, and perhaps also for NOT_BUILT.

UNKNOWN does not look suitable for any result.

### Upstream changes

[[BSERV-3219] Add 'Canceled' state for Build Statuses](https://jira.atlassian.com/browse/BSERV-3219)

**Comment by KalleOlaviNiemitalo** [comment]
According to [The Bitbucket Cloud REST API](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-commit-statuses/#api-repositories-workspace-repo-slug-commit-commit-statuses-get), the CANCELLED and UNKNOWN build states have not been added to Bitbucket Cloud. There, the valid values are SUCCESSFUL, FAILED, INPROGRESS, and STOPPED. The plugin already uses all of those. So, the behavior with Bitbucket Cloud should not be changed.

**Comment by nfalco79** [comment]
> CANCELLED would be suitable for the ABORTED result, and perhaps also for NOT_BUILT.

Why CANCELLED in Data center API would be suitable for the ABORTED result but for cloud API it is FAILED and not STOPPED (stop and abort are synonyms). Maybe I remember bad, but it's becuase STOPPED does not prevent merge?

**Comment by nfalco79** [comment]
I see that actual trait says "Do not communicate not-built jobs to Bitbucket" but it report STOPPED/CANCELLED. Label it's not clear, and there is not help description.

**Comment by rittneje** [comment]
@nfalco79 This should be considered a bug, not a feature request. The current default behavior around NOT_BUILT in Data Center is wrong and actively harmful.

**Comment by nfalco79** [comment]
How could be a bug is the time the issue was created the status in DataCenter API was new?
Anyway must be consider also:
* https://issues.jenkins.io/browse/JENKINS-44540
* https://issues.jenkins.io/browse/JENKINS-66620

**Comment by rittneje** [comment]
It's objectively a bug that the build killing itself (which reports as `NOT_BUILT`) turns into SUCCESSFUL _by default_. The build didn't actually complete, and definitely cannot count towards a merge gate. Either it should report nothing by default (and the opt-in was never needed), or it should report FAILED by default.

JENKINS-44540 is already addressed by the opt-in to report nothing. If this bug is addressed, then the opt-in may be totally superfluous.

I'm not sure how JENKINS-66620 is relevant.

**Comment by nfalco79** [comment]
> It's objectively a bug that the build killing itself (which reports as NOT_BUILT) turns into SUCCESSFUL by default.

This is your point of view, regardless of whether I agree or not, backwards compatibility is a priority. I don't want to have any more problems (now more or less **200** between github and jira), so adding configurations to cover most of the needs is the way I think is correct.

**Comment by rittneje** [comment]
@nfalco79 I cannot think of a single use case in which NOT_BUILT being reported as SUCCESSFUL is correct.

Also, backwards compatibility is not the be all and end all. Otherwise, no one could ever fix a bug in any software.

Finally, adding configuration to avoid properly fixing a bug is not the right solution. An application needs to do the safest thing by default. In this case, that is clearly to report either nothing (or FAILED). That is because today, if the build gets killed, Bitbucket will claim success in the merge gate. And unless you explicitly go to Jenkins to see that is a lie, you will think all is well and merge a PR that is totally broken. Meanwhile, if it reported nothing by default, then Bitbucket would not consider the merge gate to be satisfied, and then you would see what happened in Jenkins and see it was NOT_BUILT, and then you can change your configuration if having that report differently is desirable.

**Comment by nfalco79** [comment]
I read the [Jenkins documentation](https://javadoc.jenkins-ci.org/hudson/model/Result.html#NOT_BUILT) of NOT_BUILT that reports:
> This status code is used in a multi-stage build where a problem in earlier stage prevented later stages from building.

I also have a look what does github and gitlab plugin. Both of them report status to FAILED or ERROR.
I will change the default value in the PR hoping not to raise a storm.

**Comment by rittneje** [comment]
From personal experience, NOT_BUILT is reported if you use `disableConcurrentBuilds(abortPrevious: true)` (at least sometimes). There may be other cases too.

**Comment by nfalco79** [comment]
@rittneje an incremental build is available at
<dependency>
  <groupId>org.jenkins-ci.plugins</groupId>
  <artifactId>cloudbees-bitbucket-branch-source</artifactId>
  <version>908.v29a_314b_891c2</version>
</dependency>

Could you confirm that in DataCenter instance CANCELLED will prevent pull request merge? I can not find any documentation. Only for Cloud.
