### ISSUE TITLE
Param to bypass build status notification

### ISSUE THREAD

**Issue by KliminV** [jenkinsci/bitbucket-branch-source-plugin#650]
### What feature do you want to see added?

Let's assume we have multibranch pipeline in bitbucket monorepo which have many projects inside. Pipeline investigates pull requests and built that branches. To decrease number of runs without any result you might be interested in detecting changes made in pull request and if changes are present run build steps.
But in that scenario plugin have already sent INPROGRESS build status to bitbucket. Successful build might be false-positive flag to allow merging pull request. NOT_BUILT and checkbox disableNotificationForNotBuildJobs will lead to stay with INPROGRESS status, which blocks PR merging. 

I would like to be able disable automatic status update and do it manually in case I need it (changes are detected)
I able to implement feature myself, but need a green light from community

**Comment by m-riks** [comment]
This option is really relevant, one more use case is for example if you have many test environments, of course you can use Skip Notification Trait plugin as mentioned everywhere, but this not always work as expected, after you seed all your jobs and org folders into jenkins they might have configured to skip notifications only on org folder  level but not project itself and after that jobs are being started to build and in some cases block production bitbucket PR's due to unsuccessful build history that was actually aborted from non-prod environments.

**Comment by KliminV** [comment]
> The Bitbucket Server Integration plugin reads the "bitbucket.status.disable" system property for this purpose: [jenkinsci/atlassian-bitbucket-server-integration-plugin#324](https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/324)
> 
> Would a similar solution work in Bitbucket Branch Source, or would the feature need to be configurable in the UI?

I am not sure if this would work or not, but this is global parameter, which is nice to have, but not ideal if you already have some jobs set up, which are depends on statuses

**Comment by nfalco79** [comment]
> I would like to be able disable automatic status update and do it manually in case I need it (changes are detected)

It is documented at the end of chapter [here](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc#bitbucket-build-status)
