### ISSUE TITLE
Clarify JIRA vs GitHub issues

### ISSUE THREAD

**Issue by kwin** [jenkinsci/bitbucket-branch-source-plugin#672]
### What feature do you want to see added?

Both ways for reporting issues are outlined in https://plugins.jenkins.io/cloudbees-bitbucket-branch-source/ and the issues from Jenkins JIRA are not listed in GitHub issues (nor vice-versa).
Please consolidate so that only one central way for reporting issues is used. Otherwise there will be lots of duplicates and it is much harder to see already reported issues.

**Comment by nfalco79** [comment]
I agree, personally I prefer the JIRA way.
Maybe some plugins enable git issue to avoid people to sign up in the JIRA portal ([issues.jenkins.com](https://issues.jenkins.io/) is a server version v9.12.8 LTS). That server is not upgraded since it should migrate on cloud version to get updates with a license under payment I suppose. The same issue for maven apache JIRA where sign up has been disabled so who has an account it's ok otherwise ...

**Comment by nfalco79** [comment]
Now I can say that the default issue tracker for this repository is JIRA.
As discussed and request in the Jenkins Developer Google group I will update the README.MD

**Comment by nfalco79** [comment]
Good idea
