### ISSUE TITLE
Get PR status on build

### ISSUE THREAD

**Issue by vishalknitian** [jenkinsci/bitbucket-branch-source-plugin#744]
### What feature do you want to see added?

In multibranch pipeline, when the build gets triggered by a PR event. Keep an environment variable to get the status of the PR.

Open
Approved
Unapproved
Merged
Declined

**Comment by nfalco79** [comment]
When a build start the variable can be set only before the build starts (step `checkout scm`) after than the variable could not be set anymore.
Moreover at build time the "status" of PR can change because when I perform a review Approving or not the PR often is when the build is running.
You can obtain the information with a simple CURL step (also shell script) to call bitbucket and retrieve the information you need. For example we had implement a some PR checks in groovy to ensure "close branch" is enabled, at most 3 reviewer are set to the PR and so on.
